### ISSUE TITLE
D-trusted如何获取？

### ISSUE THREAD

**Issue by ISGuXing** [Los-Phoenix/NFETC-FCLC#1]
请问你们是如何识别获得D-trusted的呢？是人工标注的吗？

**Comment by Los-Phoenix** [comment]
在本文实验中，三个数据集的原本训练集都是有人工标注和远监督数据两个部分的，只不过人工标注的数量较少，其它研究把两部分合在一起拿来训练。
我们把其中的人工标注部分用作D_{trusted}。具体的数据划分可以参见我们的代码（会稍晚放出），也可以参见NFETC的预处理代码。

在实际使用中，正如我们的子实验所论述的，所需要的D_{trusted}数量很少，使用人工标注，甚至专家标注都是可行的。

**Comment by ISGuXing** [comment]
好的，已经清楚了，谢谢你的回答，very thankful！
