### ISSUE TITLE
gt_portion是什么参数

### ISSUE THREAD

**Issue by guoli-afk** [Los-Phoenix/NFETC-FCLC#2]
运行python eval4test.py -m wikim -d wikim -r 5 -a 0.4时出错了
![image](https://user-images.githubusercontent.com/63287138/206396394-ecc66aa4-38eb-4eec-8c0f-21068a0c6f09.png)

**Comment by Los-Phoenix** [comment]
gt_portion是调整使用gt集合的何种比例来参与训练的参数。对应论文中的图4.
对于一般实验，建议把命令行调整为

`python eval4test.py -m wikim -d wikim -r 5 -a 0.4 -gt_portion 1 `

即可

很抱歉我暂时没有调试代码和上传的条件，待开发环境允许后会修改代码版本。

期待你的复现和反馈。
